name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - production

jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # reads from .ruby-version
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rake rubocop
  # js:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.2.0

  #     - name: Cache dependencies
  #       uses: actions/cache@v2
  #       with:
  #         key: npm-${{ hashFiles('./package-lock.json') }}
  #         path: ~/.npm
  #         restore-keys: |
  #           npm-

  #     - name: Install dependencies
  #       run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline

  #     - name: Prettier & eslint
  #       run: npm run lint:test
